services:
  - type: static
    name: sena-inventario-frontend
    env: static
    buildCommand: |
      npm install
      chmod +x node_modules/.bin/react-scripts
      npm run build
    staticPublishPath: build
    rootDir: frontend
