# Generated by Django 5.2 on 2025-04-23 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(max_length=100)),
                ('piso', models.CharField(max_length=20)),
                ('tipo_ambiente', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEnergetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('correo_usuario', models.EmailField(max_length=254)),
                ('categoria_base', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
                ('frecuencia_uso', models.CharField(max_length=50)),
                ('horas_dia', models.IntegerField()),
                ('dias_mes', models.IntegerField()),
                ('potencia_w', models.FloatField()),
                ('voltaje_v', models.FloatField()),
                ('corriente_a', models.FloatField()),
                ('consumo_kwh_mes', models.FloatField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.centro')),
            ],
        ),
        migrations.AddField(
            model_name='ambiente',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.sede'),
        ),
    ]
