# Generated by Django 5.2 on 2025-04-25 16:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroenergetico',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Registro Energético', 'verbose_name_plural': 'Registros Energéticos'},
        ),
        migrations.RemoveField(
            model_name='registroenergetico',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='registroenergetico',
            name='subcategoria_1',
            field=models.CharField(default='General', help_text='Subclasificación principal del equipo/consumo', max_length=100, verbose_name='Subcategoría Nivel 1'),
        ),
        migrations.AddField(
            model_name='registroenergetico',
            name='subcategoria_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategoría Nivel 2'),
        ),
        migrations.AddField(
            model_name='registroenergetico',
            name='subcategoria_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategoría Nivel 3'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.ambiente', verbose_name='Ambiente Relacionado'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='categoria_base',
            field=models.CharField(max_length=100, verbose_name='Categoría Principal'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='consumo_kwh_mes',
            field=models.FloatField(editable=False, verbose_name='Consumo kWh/mes'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='correo_usuario',
            field=models.EmailField(max_length=254, verbose_name='Correo del Responsable'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='corriente_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Corriente (A)'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='dias_mes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Días por Mes'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='frecuencia_uso',
            field=models.CharField(max_length=50, verbose_name='Frecuencia de Uso'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='horas_dia',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Horas por Día'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='potencia_w',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potencia (W)'),
        ),
        migrations.AlterField(
            model_name='registroenergetico',
            name='voltaje_v',
            field=models.FloatField(blank=True, null=True, verbose_name='Voltaje (V)'),
        ),
    ]
