# Generated by Django 5.2 on 2025-04-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_registroenergetico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenergetico',
            name='refrigerante',
            field=models.CharField(blank=True, choices=[('R22', 'R-22'), ('R410A', 'R-410A'), ('R32', 'R-32'), ('R134A', 'R-134A')], max_length=50, null=True, verbose_name='Tipo de Refrigerante'),
        ),
        migrations.AddField(
            model_name='registroenergetico',
            name='tipo_aire',
            field=models.CharField(blank=True, choices=[('SPLIT', 'Split'), ('VENTANA', 'De Ventana'), ('PORTATIL', 'Portátil'), ('CENTRAL', 'Sistema Centralizado')], max_length=50, null=True, verbose_name='Tipo de Aire Acondicionado'),
        ),
    ]
