# Generated by Django 5.2 on 2025-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_remove_ambiente_sede_ambiente_sede_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenergetico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_registros/'),
        ),
    ]
