# Generated by Django 5.2 on 2025-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_rename_imagen_1_registroenergetico_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroenergetico',
            old_name='imagen',
            new_name='imagen_1',
        ),
        migrations.AddField(
            model_name='registroenergetico',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_registros/'),
        ),
    ]
